export const userTypes = {
	GET_USER: 'GET_USER',
	UPDATE_USER: 'UPDATE_USER',
	USER_LOADING: 'USER_LOADING'
};

export const colorTypes = {
	GET_SWATCHES: 'GET_SWATCHES',
	GET_PALETTES: 'GET_PALETTES',
	GET_GRADIENTS: 'GET_GRADIENTS',
	ADD_SWATCH: 'ADD_SWATCH',
	ADD_PALETTE: 'ADD_PALETTE',
	ADD_GRADIENT: 'ADD_GRADIENT',
	UPDATE_COLOR: 'UPDATE_COLOR',
	COLOR_LOADING: 'COLOR_LOADING'
};
