export const userTypes = {
	GET_USER: 'GET_USER',
	USER_LOADING: 'USER_LOADING'
};

export const colorTypes = {
	GET_SWATCHES: 'GET_SWATCHES',
	GET_PALETTES: 'GET_PALETTES',
	GET_GRADIENTS: 'GET_GRADIENTS',
	COLOR_LOADING: 'COLOR_LOADING'
};
